### ISSUE TITLE
Error parsing attribute with whitespace

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#100]
## Error in Client API

**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**
[400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [published]"}],"type":"mapper_parsing_exception","reason":"failed to parse [published]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \" \n\t\t2017\n\t\""}},"status":400}

[View on Bugsnag](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b6848f9002a3fc782dc0000&i=gh&m=ci)

## Stacktrace

    app/jobs/index_job.rb:5 - perform

[View full stacktrace](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b6848f9002a3fc782dc0000&i=gh&m=ci)

*Created by Martin Fenner via Bugsnag*

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7a89f6002acc164e4a0000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7a8ce8002ac4dcdb3e0000&i=gh&m=ra)

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7a8d61002acdea02cc0000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7a9393002ac4e63ef30000&i=gh&m=ra)

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7a96a3002acdf6d5d70000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7a9a72002ac8e350ea0000&i=gh&m=ra)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7ad304002ce34836040000&i=gh&m=eu)

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7ad360002ac511755c0000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7adeab002ce0f4c6da0000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7bc66f002accfb0bde0000&i=gh&m=ra)

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7bd1a1002acdc1e1b90000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b7e61b4002ac85788cd0000&i=gh&m=ra)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b81855f002dc8a089760000&i=gh&m=eu)

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b81d373002df45225120000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b8a6d52002dc506e7bf0000&i=gh&m=ra)

**Comment by mfenner** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5b8a6d52002dc506e7bf0000&i=gh&m=fx)

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Elasticsearch::Transport::Transport::Errors::BadRequest** in **app/jobs/index_job.rb:5**](https://app.bugsnag.com/datacite/client-api/errors/5b684677ff1be4001a786021?event_id=5bce2c79003090f4e7060000&i=gh&m=ra)

**Comment by richardhallett** [comment]
Old issue, believe fixed elsewhere. 
Can not see same errors in sentry.
