### ISSUE TITLE
Upgrade Rails Version 6.1 -> 7.1

### ISSUE THREAD

**Issue by wendelfabianchinsamy** [datacite/lupo#1094]
Rails 7.1 comes with many performance improvements. One that is interesting to us is the `load_async` method on Active Record models. 

This will work in conjunction with Ruby upgrade -> https://github.com/datacite/lupo/issues/1095

Guide for upgrading to Rails 7.0 -> https://www.fastruby.io/blog/rails/upgrades/upgrade-rails-6-1-to-7-0.html

RaIls 7 has included various performance improvements -> https://seemlight.medium.com/a-comprehensive-comparison-rails-6-vs-rails-7-eebe5c6888f9#:~:text=Performance%20Enhancements%3A,execution%2C%20resulting%20in%20improved%20performance.

**Comment by jrhoads** [comment]
@wendelfabianchinsamy I think this is finished right?
