### ISSUE TITLE
To investigate ActiveRecord::RecordNotUnique in dois#update

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#113]
## Error in Client API

**ActiveRecord::RecordNotUnique** in **dois#update**
Mysql2::Error: Duplicate entry '10.6084/M9.FIGSHARE.7138913.V1' for key 'doi': INSERT INTO `dataset` (`created`, `doi`, `is_active`, `updated`, `version`, `datacentre`, `url`, `aasm_state`, `source`) VALUES ('2018-09-27 04:16:32', '10.6084/M9.FIGSHARE.7138913.V1', x'01', '2018-09-27 04:16:32', 0, 31042, 'https://figshare.com/articles/Additional_file_1_of_Intrafollicular_fibroblast_growth_factor_13_in_polycystic_ovary_syndrome_relationship_with_androgen_levels_and_oocyte_developmental_competence/7138913/1', 'findable', 'mds')

[View on Bugsnag](https://app.bugsnag.com/datacite/client-api/errors/5b8ac8daa33cf70018d6946a?event_id=5bac59a0002f93204a950000&i=gh&m=ci)

## Stacktrace

    app/controllers/dois_controller.rb:251 - update

[View full stacktrace](https://app.bugsnag.com/datacite/client-api/errors/5b8ac8daa33cf70018d6946a?event_id=5bac59a0002f93204a950000&i=gh&m=ci)

*Created by Kristian Garza via Bugsnag*

- [ ] To define issue problems

**Comment by richardhallett** [comment]
This is a difficult bug to track down especially as this hasn't happened for over a month.
I've tried to re-create with similar MDS calls but nothing seems to cause the recordnotunique error.

Ive not managed to re-create therefore I'm going to close, if this bug does however re-appear we can potentially look into more scenarios.
