### ISSUE TITLE
Investigate misassignment of prefixes

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#128]
Prefixes 10.17021 and 10.17187 were inadvertently assigned to two different providers.

As we can't rule out that something similar has happened with other prefixes, we will do an investigation of all our prefixes with registered DOIs, and whether there are any similar issues.

**Comment by richardhallett** [comment]
We want to determine if a prefix has been used by different clients to register dois.

**Comment by richardhallett** [comment]
Looking through our DB there are indeed some cases where a DOI's have been registered to a prefix belonging to different clients, presumably at different times.
But then I thought about this and isn't this fine? like as long as it's not at the same time, isn't it up to the provider to decide how their prefixes get assigned out? Perhaps im misunderstanding the problem.

**Comment by mfenner** [comment]
This is probably fine in most cases, e.g. when some DOIs have been transferred to another client. But it can be a problem, and we want to make sure we identify the problematic ones.

**Comment by richardhallett** [comment]
I've attached a CSV
[prefixes-dois-by-client191118.txt](https://github.com/datacite/lupo/files/2595545/prefixes-dois-by-client191118.txt)
 that shows all the clients and the prefixes that are used by them, plus the number of DOI's registered to them.
As I said in previous comment this to me looks fine, it's not just about prefix transfers, within a provider they are free to switch a prefix arn't they?
If this is not what we're after can we try and narrow down exactly what we're trying to ascertain.

**Comment by richardhallett** [comment]
Actually I can narrow this down a bit more so it's a bit more relevant.
Here is are the Prefixes that have DOI's registered against them across different providers

10.5072 | 44
-- | --
10.3334 | 4
10.506 | 3
10.1301 | 2
10.5967 | 2
10.17021 | 2
10.4231 | 2
10.5073 | 2
10.3205 | 2
10.1594 | 2
10.2314 | 2
10.17187 | 2
10.5438 | 2
10.4225 | 2
10.2538 | 2

If we look at the first one and then corrolate with the previous CSV we can see that 10.3334 was used by OSTI, NOAA, CDL and ORNLDAAC.
This correlates with what you can find by DOI search in fabrica: https://doi.datacite.org/dois/dois?client-id=&prefix=10.3334&query=

However it is a prefix that is now currently only assigned to ORNLDAAC so this was assigned to different providers previously, is this a problem or not?

**Comment by richardhallett** [comment]
Further conversation based on the above table that shows all prefixes shared between providers.
We need to understand if these are fine
* Were they part of a prefix transfer
* Are they currently assigned to multiple providers

**Comment by richardhallett** [comment]
Looking at the above prefixes and the data and across our history of prefix transfers, I can see no other potential misassigned prefixes in their current state.
