### ISSUE TITLE
Client appears on /show but not on /index?query:

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#132]
very likely the client was created in MDS UI. So its only in the database but not in ES

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_facr)

**Comment by kjgarza** [comment]
![image](https://user-images.githubusercontent.com/1092861/48478523-d40dfd80-e804-11e8-881e-22dd58a599d7.png)

it seems the client was deleted in april

**Comment by mfenner** [comment]
This issue has been resolved.
