### ISSUE TITLE
https://api.datacite.org/works?include=... produced error 500

### ISSUE THREAD

**Issue by uschindler** [datacite/lupo#154]
Hi, when accessing the following URL to get all works for a specific datacenter, I get a 500 error:

https://api.datacite.org/works?include=tib.pangaea

The documentation is not very clear how this should look like. "include: comma-separated list from data-center, member and resource-type" ????

**Comment by mfenner** [comment]
The `include` is from the JSONAPI spec (https://jsonapi.org/format/#document-compound-documents), is for sideloading, and should be the entity name(s). Allowed values here are `data-center`, `member`, `resource-type`, e.g. https://api.datacite.org/works?include=data-center,member. This query will return `works` in the `data` JSON object, and metadata about the data centers and members for those works in the `included` JSON object.

**Comment by uschindler** [comment]
Sorry ignore this, was a misunderstanding. I was looking for:

https://api.datacite.org/clients/tib.pangaea/dois

All fine, you can close.

**Comment by mfenner** [comment]
Ok. But please don't use last_update date, as this can change for many reasons, not just metadata and/or URL updates.

**Comment by uschindler** [comment]
I have to wait for deep paging. It stops at page 400 :-(

**Comment by uschindler** [comment]
Hi @mfenner 
Is the cursor functionality not yet enabled in the productive version? The link provided as "next" is still using paging and is not using cursor: https://api.datacite.org/clients/tib.pangaea/dois

**Comment by mfenner** [comment]
The cursor is currently only available to staff users, as we are doing final tweaks to the Elasticsearch index. The cursor should be available no later than January 2nd.
