### ISSUE TITLE
support nested queries for DOIs

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#189]
Implementing https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html

As this requires changes in the index - which come with some downsides - we need to define use cases.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_wber)

**Comment by mfenner** [comment]
First use case is to search for subject and subjectScheme.

**Comment by hrzepa** [comment]
Can I leave examples of nested queries

https://api.datacite.org/dois?query=(subjects.subjectScheme%3Ainchikey+AND+subjects.subject%3AKTOSDSJYNBIDCN-UHFFFAOYSA-N)+AND+(subjects.subjectScheme%3AGibbs_Energy+AND+subjects.subject%3A%22-1082.980914%22)

restricts the subject content search (KTOSDSJYNBIDCN-UHFFFAOYSA-N) to only those records for which the subjectscheme has the value inchikey  AND for which the subject content -1082.980914 has the subjectscheme Gibbs_Energy

Transposing the two subjectschemes, as below, should not lead to any positive returns

https://api.datacite.org/dois?query=(subjects.subjectScheme%3Ainchikey+AND+subjects.subject%3A%22-1082.980914%22)+AND+(subjects.subjectScheme%3AGibbs_Energy+AND+subjects.subject%3AKTOSDSJYNBIDCN-UHFFFAOYSA-N)

Currently,  BOTH searches yield the same result, which is wrong.

**Comment by hrzepa** [comment]
I gather the fix is currently in the test system.  When will it reach the production system?

**Comment by mfenner** [comment]
No, this work has not started. And the queries you need for `subject` can also be implemented differently, not using nested queries.

**Comment by hrzepa** [comment]
Do please show how to refactor these queries, Martin.

**Comment by mfenner** [comment]
Not refactor, but index differently, creating a new index field that combines subjectScheme and subject. @uschindler suggested that to me, but I have not yet found time to implement.
