### ISSUE TITLE
Updating attributes when metadata is invalid

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#193]
When attempting to use the REST API to update attributes other than the raw metadata, e.g. landingPage, if you are trying to update an existing findable DOI that has metadata that is not actually valid, then the update call will fail.

The problem is mostly due to old doi's rather than newly created ones.

This has an effect when you are just trying to update some other data than just the metadata.

Is it possible that we can potentially ignore trying to validate the metadata when not actually updating it?

**Comment by mfenner** [comment]
While I understanding the reasoning, I think we should rather fix the underlying problem of findable metadata that are not valid.

**Comment by richardhallett** [comment]
I agree that it's important to fix underlying metadata, however I'm not sure how we can systematically do this without playing wack-a-mole (i.e. fixing them on a case by case basis)

Additionally given we're not the original source of the metadata, can we reliably fix the issues that might crop up?

I feel that our when you're updating data that is not related it is potentially confusing to return errors about an unrelated area, i.e. in this case metadata validation.

**Comment by mfenner** [comment]
We need to systematically address the valid metadata issue. There are several factors contributing to valid metadata issues, from recent changes to the REST API to DOIs registered in the early days of the MDS. 

It is our responsibility to provide valid metadata, as our services depend on that.

The only example we currently have for updating a DOI record and not metadata is the link checker, and that is an internal application, so I don't worry too much about confusion.

**Comment by richardhallett** [comment]
I think that's the problem I forsee, if we have invalid metadata, is it our responsibility? I mean we are infrastructure and we provide tools for validation but the metadata source comes from elsewhere.

Also as for another example, this also can occur when attempting to update the URL.
See https://github.com/datacite/datacite/issues/671 for a new issue where someone is attempting to update old DOI's and are receiving metadata invalidation problems.

**Comment by richardhallett** [comment]
Internal Discussion notes:
Agreed that this is something that needs wider investigation however we might need a pragmatic approach depending on the use case.
This should be looked at as part of the Form work as it's closely linked to the API and how this works.

* Consider error messages returned
* Consider allowing URL updates if nothing else changes.

**Comment by richardhallett** [comment]
As an additional this also does effect sometimes file upload to for same reasoning.
For example when attempting to update a URL with now an invalid schema, the schema invalidates.
For the form it just throws an error, so we need to consider this usecase.

![image](https://user-images.githubusercontent.com/7294431/53108781-e56b5200-3537-11e9-9bf5-6e8c9076f204.png)

**Comment by richardhallett** [comment]
As it does sometimes cause user confusion however, I've added the bug label for us to consider the wider impact. We should decide on how we want to move forward with this in Fabrica.

The question is based on previous discussions do we:

1) Change the validation requirements to allow URL changes when the metadata has not been changed.

2) Add additional error messaging as part of validation process so people are aware of more specifics of what's happening, even if they are trying to update just the URL.

**Comment by mfenner** [comment]
I prefer option 2.

**Comment by richardhallett** [comment]
It's worth pointing out, there was some feedback from a user where they do not wish to update the schema to a newer version but do want to change just the URL. I guess we need to standardise our response if the only option is for them to update.

**Comment by mfenner** [comment]
If this is about schema 2.x, then the alternative is to support metadata updates with schema 2.x.

**Comment by richardhallett** [comment]
This issue conflates a few different scenarios, so to avoid confusion closing this in favour of more specific issues that can address the problem.

The main summary output from this in general however is that while there are scenarios for updating other data other than metadata, it is preferable for the default to be to always validate as we want to encourage valid metadata.
