### ISSUE TITLE
API Docs - does not use correct JSON API format

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#209]
The autogenerated API docs that let you try in the browser e.g.
https://support.datacite.org/reference/dois-2#post_dois
Do not follow JSONAPI as they are missing the enclosing "data" element around the payload.

I'm not sure if this is for all tests or just the above example.

**Comment by mfenner** [comment]
Fixed via https://github.com/datacite/lupo/commit/4b0ac8101e1b17f400326017404a47bf71a04f96.
