### ISSUE TITLE
Investigate difference between SOLR and ES for HEPData

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#211]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hoar)

**Comment by kjgarza** [comment]
https://docs.google.com/spreadsheets/d/1dals8_srmRnlyc_NZQjLXNc7hGhI1UeSJW_9rKeiOnY/edit#gid=0

this is the brakdown of the DOI in the database. I am leaning to belive that there are ~30k dois that are not indexed in the ES index. 

https://api.datacite.org/clients/cern.hepdata/dois?page[size]=0


total: 222471,

**Comment by kjgarza** [comment]
we will need to try 

```
export CLIENT_ID=cern.hepdata
bundle rake  client:index_all_dois
```

and check if we find something. At the moment I having problins to adding the new pubucli_key to login into fargate. I'll need to re-acheck how to do it.

**Comment by mfenner** [comment]
Let's talk about how best to do that. I am not sure the above command is the right one.

**Comment by kjgarza** [comment]
I re-cheked the distribution and I think i found the DOIS. They are definetely not indexed .

one can see them with:

```
SELECT COUNT(Id), is_active, aasm_state, indexed, creators
  FROM dataset
WHERE datacentre = "30764" && year(indexed) = "1970"
GROUP BY is_active, aasm_state, day(indexed)
```

29580	0	findable	1970-01-01 00:00:00.000	


need to be imported

**Comment by kjgarza** [comment]
actually the problem was about doi not in registered state, when the yshould. We change all the DOIS to the correct state in sql (registered) and reindex the index.
