### ISSUE TITLE
REST API - rightsList denying lang attribute

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#226]
When sending a JSON API with attributes, the "rightsList" attribute should support the "lang" sub 

attribute, documentation suggests this is allowed but is currently not validating.

```
"rightsList": [
  {
     "rightsUri": "http://example.com",
     "lang": "en"
  }
],
```

Should be allowed

**Comment by thackerc** [comment]
The documentation at [https://support.datacite.org/reference/dois-2#put_dois-id](https://support.datacite.org/reference/dois-2#put_dois-id) shows this as a valid field.

**Comment by mfenner** [comment]
This has been fixed.
