### ISSUE TITLE
REST API - Subjects is denied with validation

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#228]
Subjects is documented as allowed via POST/PUT in the API, however with using PUT and validation this is being denied.

```
"subjects": [
{
  "subject": "Zoning."
},
{
  "subject": "Geographic information systems."
}
],
```

Schema does support multiple subjects and attributes should reflect this.

**Comment by thackerc** [comment]
@richardhallett can you give any clue to when this will be addressed?

**Comment by mfenner** [comment]
This has been fixed.
