### ISSUE TITLE
Unable to delete providers when there exists deleted clients

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#229]
Unable to trigger a delete of a provider, even if the clients have all been deleted.
This appears in Fabrica, but is the API that is the problem.

Specifically our code looks for all clients including those marked as deleted within the index, this is done by the "countable" concern which does a query with "include_deleted"
See: https://github.com/datacite/lupo/blob/master/app/controllers/concerns/countable.rb#L20

The concern is used not just by delete, but also as part of the count shown for providers.

I think we should never include deleted and change this, but @mfenner what are your thoughts on this?

**Comment by mfenner** [comment]
We need to include the deleted clients in the count shown to providers, to keep track of the number of clients over time, which is relevant for billing.

We should have logic that a provider can be "deleted" when all clients have been "deleted".
