### ISSUE TITLE
Add creating/updating multiple contact information per provider

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#244]
Add support for storing multiple contacts against a provider
Each contact should have a type associated with it:
Known types:
* Billing
* General
* Technical
* Service
* Voting

*Contact information*:
* Email
* Given Name
* Family Name

You should be able to 
Create/Update - For an individual provider add/edit this information - Authorised only
Get - For an individual provider retrieve this information - Authorised only

**Comment by mfenner** [comment]
I suggest to have a separate table for contacts with the following information:

* given name
* family name
* email
* role (one or multiple, including billing, technical, service, voting)

Going forward we can think about linking those contact records to authentication.

**Comment by mfenner** [comment]
@daslerr and @richardhallett should we include all roles of people interacting with us, e.g. in support? In addition to what we have now that might include `repository manager`. 

And if we have multiple contacts with the same role, should we include a priority (e.g. primary billing contact, secondary billing contact)?

**Comment by richardhallett** [comment]
I'd keep the contact "roles" to a minimum at this point, just the ones highlighted above.
I'd also only have one role per contact, or I think it'll be more confusing. We can also then be specific in say the provider form and show exactly the contact types we care about, rather than letting them add multiple combinations which will get complicated and possibly more confusing.

**Comment by mfenner** [comment]
Agree.

**Comment by mfenner** [comment]
We should align with the Salesforce data model to make data exchange straightforward. Salesforce allows a contact to be associated with more than organization.

https://trailhead.salesforce.com/en/content/learn/modules/admin_intro_accounts_contacts/admin_intro_accounts_contacts_relationships

**Comment by richardhallett** [comment]
Thinking more on this, I don't think we should try and build a complicated many to many contact details relationship here as it's going to be require a fair amount of work to get this to make sense for our current model.

I think it's going to be simpler to setup a one to many.
i.e. A provider has many contacts.

This also I think makes sense for future considerations that contacts might be used as part of any authentication scheme, making a contact unique and allowing that to belong just one provider allows for relatively easy "this contact email is a provider x account email and can be used to login"

I'm also not sure of the use case where a contact might belong to different providers.

**Comment by mfenner** [comment]
I agree. Let's move forward with a one-to-many data model for providers and contacts. I would call the internal model `User` rather than `Contact` to have a path forward when we implement authentication in a few months.

**Comment by richardhallett** [comment]
After discussions and due to the complexity and potential changes we want to do in the future around accounts, it was decided for the base requirements to add individual new fields to the providers model without an additional table or role lookup.
