### ISSUE TITLE
Add creating/updating billing address for a provider 

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#245]
Add support to the provider API endpoints to allow storing and updating a billing address.

Add/Update - Authorised only
Get - Authorised Only

Fields needed:

Street Address
City
State/Province
Zip/PostCode
Country

**Comment by kjgarza** [comment]
Street Address -> ????
City ->                   ?????
State/Province -> ????
Zip/PostCode ->  ?????
Country -> country_code

I think there is still an open question on whether this information whether have its own individual field in the database. Considering only the use case of storing and displaying this information,  I would suggest to have all this information in a single field as a JSON blob, `billing_information` . any cooments?  @mfenner

**Comment by kjgarza** [comment]
closed in https://github.com/datacite/lupo/pull/248
