### ISSUE TITLE
Unable to update landingPage attribute for invalid metadata

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#246]
This is related to the conversations that happened in #193.

When the automated link checker crawler (lambda script) attempts to store landing page result check information via api.datacite.org/dois/{doi} sometimes this will fail with an error from the api, when investigating these errors this for a wide selection is related to invalid metadata trying to be validated.

Examples:
[ERROR]	2019-04-17T10:02:19.102Z	a0bebf56-f97b-43fa-8590-ee0283d9d052	Unexpected error, pushing back onto redis, Failed to send result to DataCite API, reason: Can't be blank
[ERROR]	2019-04-17T10:02:01.255Z	a0bebf56-f97b-43fa-8590-ee0283d9d052	Unexpected error, pushing back onto redis, 'ascii' codec can't encode character '\xe4' in position 32: ordinal not in range(128)

Other errors can be seen in our logs:
https://app.datadoghq.com/logs?cols=core_host%2Ccore_service%2Clog_elb.performance.backend_processing_time%2Clog_duration&event&from_ts=1552904563912&index=main&live=true&query=%40aws.awslogs.logGroup%3A%22%2Faws%2Flambda%2Fstore-crawler-results%22+error&stream_sort=desc&to_ts=1555496563912

**Proposal:**
Allow system updates to bypass validation in the API, we could implement this via checking if it's a staff account trying to make the call. @mfenner thoughts?

**Comment by richardhallett** [comment]
@mfenner Did you have further thoughts on this? 

Requests are still rejected as you can see by the original datadog link.

I am still strongly in favour of bypassing metadata validation for system level updates, the reason being is that even if there validation errors within metadata, it would be better to provide the information we have collected regarding the landing page status, this may even help identify potential errors people need to fix.

There is also the possibility that we would want some kind of process to be able to update these records to flag potential problems with metadata, perhaps in relation to the metadata quality tool work.

**Comment by mfenner** [comment]
I still disagree. I have found that we have resolved almost all invalid metadata by now, and that they show up in unexpected ways otherwise.

Something we could consider it storing landing page information somewhere else to better separate these "system level metadata". For example in a different table with a 1-1 relationship. But not as high urgency.

**Comment by richardhallett** [comment]
I wasn't considering where we store the data as part of this problem, more that conceptually what an update to a DOI is, there is already other data associated to a DOI that is not specifically related to "DOI DataCite metadata".

However if it would make things clearer to separate this, then I could see that working, and instead you would update the system information around a DOI or something.

Okay will close in favour of further discussion around general additional system level metadata/information.
