### ISSUE TITLE
ArgumentError in data_centers#index

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#25]
## Error in Client API

**ArgumentError** in **data_centers#index**
wrong number of arguments (given 0, expected 2)

[View on Bugsnag](https://app.bugsnag.com/datacite/client-api/errors/5a1715c59dd1a900181d23a2?event_id=5a356a34fcef750019c671ff&i=gh&m=ci)

## Stacktrace

    app/controllers/concerns/facetable.rb:5 - client_year_facet
    app/controllers/data_centers_controller.rb:35 - index

[View full stacktrace](https://app.bugsnag.com/datacite/client-api/errors/5a1715c59dd1a900181d23a2?event_id=5a356a34fcef750019c671ff&i=gh&m=ci)

*Created by Martin Fenner via Bugsnag*

**Comment by mfenner** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ArgumentError** in **data_centers#index**](https://app.bugsnag.com/datacite/client-api/errors/5a1715c59dd1a900181d23a2?event_id=5a5a1611aff021001bf99da1&i=gh&m=ra)

**Comment by kjgarza** [comment]
@mfenner I guess i forgot to do the release but... you have not made relases of Lupo recently right. The last one is from dec 17th
