### ISSUE TITLE
Billing information bit Feedback 

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#273]
- [x] Should export ISO country code instead of country name for `country` and `billingCountry`
- [x] Map Member types to new types  (for role field)

**Comment by kjgarza** [comment]
@mfenner just to confirm the roles map to labels in the CSV like this:

```
    { "ROLE_MEMBER" => "Member Only",
      "ROLE_ALLOCATOR" => "Member Provider",
      "ROLE_CONSORTIUM_LEAD" => "Consortium Lead",
      "ROLE_CONTRACTUAL_PROVIDER" => "Contractual Provider",
      "ROLE_FOR_PROFIT_PROVIDER" => "For-profit Provider "
     }

```

**Comment by mfenner** [comment]
Looks good. There is work to do in a few places in the API.

**Comment by kjgarza** [comment]
I think the whole member type requirement needs further specification. this is what I think it looks like but I owuld like to hear comments



| Role_name                 | Member_type          | CSV Label for Member_type | Abilities in Fabrica | Should show up in DOI fabrica? |
|---------------------------|----------------------|---------------------------|----------------------|--------------------------------|
| ROLE_MEMBER               | member_only          | Member Only               | ??????               | No                             |
| ROLE_ALLOCATOR            | member_provider      | Member Provider           | provider_admin       | Yes                            |
| ROLE_CONSORTIUM_LEAD      | consortium_lead      | Consortium Lead           | provider_admin       | Yes                            |
| ROLE_CONTRACTUAL_PROVIDER | contractual_provider | Contractual Provider      | provider_admin       | Yes                            |
| ROLE_FOR_PROFIT_PROVIDER  | for_profit_provider  | For-profit Provider       | provider_admin       | Yes                            |

**Comment by kjgarza** [comment]
- [ ] Validate @ in twitter-handle in a different way
- [ ] change spelling GB English
- [ ] help text in every field of billing information

**Comment by mfenner** [comment]
To be clear, spelling should be US English.

**Comment by kjgarza** [comment]
@daslerr I guess there are no more comments about this? Could we close it?

The billing contacts are managed in https://github.com/datacite/lupo/issues/278
