### ISSUE TITLE
Usage doesn't show on results list in DataCite Search

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#293]
https://search.datacite.org/works?query=%2210.7272%2Fq6g15xs4%22

Results List  of usage requires to get a list of event based on a list of dois. Previously in `lagottino` this was done by using find_by_ids. See:

https://github.com/datacite/lagottino/blob/6721367df3c59387fe188c30788db62b6af5355c/app/models/concerns/indexable.rb#L71

However, now in lupo that needs to be implemented :

https://github.com/datacite/lupo/blob/e879713ac8b4f4d168278a3ff32c720358f66ed7/app/controllers/events_controller.rb#L83

https://github.com/datacite/lupo/blob/e879713ac8b4f4d168278a3ff32c720358f66ed7/app/models/event.rb#L84

as the current method requires `uuids` which the front-end interface does not know

https://github.com/datacite/lupo/blob/e879713ac8b4f4d168278a3ff32c720358f66ed7/app/models/event.rb#L283

**Comment by mfenner** [comment]
`find_by_ids` was a very confusing implementation, as it was not a find by id/uuid. You want `find_by_dois`. Please don't conflate the two with events.

**Comment by mfenner** [comment]
```
response = Event.query(nil, doi: params[:doi], page: page, sort: sort) 
```

**Comment by kjgarza** [comment]
confirmed we can use `/events?doi=` instead of `/events?ids=` to obtain the same data
