### ISSUE TITLE
When calling events and adding include=subj,obj the included objects have no metadata

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#294]
### Expected Behaviour

When calling events and adding include=subj,obj it should return a list of objects with basic DOI metadata

### Current Behaviour

it returns a list og objs with empty metadata.
 ![Screenshot 2019-04-09 at 11.14.02.png](https://images.zenhubusercontent.com/57c7eecee40e5714b16e1fe7/4aa38a56-9105-4403-9540-4d75d9ccd320)

### Steps to Reproduce

1. call https://api.datacite.org/events?doi=10.15468/dipjcr&include=subj,obj
2. look at the included array

### Context (Environment)

Production enviroment. Both v1 and v2 Eventdata API have the same issue

### Hypothesis

a) metadata is not indexed in events index
b) EventData agent is not sending the metadata or is wrongly formatted
c) Lagottino Serialiser is not showing

**Comment by kjgarza** [comment]
previously https://github.com/datacite/lagottino/issues/32

**Comment by mfenner** [comment]
We switched to including doi metadata instead (#296).
