### ISSUE TITLE
Including DOIs with events has n+1 problem

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#300]
DOI metadata are currently fetched individually for every single event.

**Comment by mfenner** [comment]
I suggest trying the `batch-loader` gem, the relevant call has been out into a `BatchLoaderHelper` concern.

Alternatively, fetch DOI metadata in a separate API call, getting the list of DOIs from the Events API call and using `DOI.find_by_id` with the list of these IDs.

**Comment by kjgarza** [comment]
In terms of the performance with batch loading. its 2-3 times faster.
So for the following query for a single DOI events/doi=10.6084/m9.figshare.1407_api_024&include=dois
The response includes 25 events and metadata for 25 DOIs. 

*batch loading: enable*

- 555.4705770045985 ms
- 561.8573510000715 ms
- 581.7548199993325 ms

*batch loading: disabled (DOI.find_by_id )*

- 1741.6881399985868 ms
- 1897.1143399976427 ms
- 1019.5500019981409 ms

Currently, we batch on the `event-id` but we can even improve that if we batch in the `citation-id`. But It will only help when there are inverse-relationships in the response. Nevertheless, the change is rather quick.

**Comment by mfenner** [comment]
Thank you @kjgarza. Can you do more extensive benchmarking, e.g. with `/events`?

**Comment by kjgarza** [comment]
Here its a comparison including three cases: batch-loading enable, batch-loading disabled, and no includes. `No includes` can be seen as some sort baseline as it is time to generate render the events only.


| Batchload enabled                              | No Batchload          | No includes           |
|------------------------------------------------|-----------------------|-----------------------|
| 636.7445210003098 ms                           | 1108.4226549996856 ms | 515.4397269998299 ms  |
| 646.7472290000842 ms                           | 1052.263457999743 ms  | 505.16649900009725 ms |
| 601.9417900001827 ms                           | 1177.9191269997682 ms | 525.0137150001137 ms  |
|                                                |                       |                       |
| /events?doi=10.6084%2Fm9.figshare.1407_api_024 |                       |                       |
| Batchload enabled                              | No Batchload          | No includes           |
| 555.4705770045985 ms                           | 1741.6881399985868 ms | 605.3901689997474 ms  |
| 561.8573510000715 ms                           | 1897.1143399976427 ms | 546.6860540000198 ms  |
| 581.7548199993325 ms                           | 1019.5500019981409 ms | 469.34482200003913 ms |
|                                                |                       |                       |
| /events?doi=10.15468%2F6e8nje (production)     |                       |                       |
| Batchload enabled                              | No Batchload          | No includes           |
| 955.69072100011 ms                             | 1682.0059149999906 ms | 847.9210939999575 ms  |
| 967.5542840000162 ms                           | 2639.2843549999725 ms | 754.9383040000066 ms  |
| 940.0102209999659 ms                           | 1881.1061810001775 ms | 910.0137150001137 ms  |

**Comment by mfenner** [comment]
Thank you @kjgarza. How did you measure these times, with a client or in the server application? And what is the query for the first three results?

**Comment by kjgarza** [comment]
@mfenner The first one is for `/events` endpoint, (it got cropped out for some reason).  All these are directly in the server application. My benchmark with the AB its bugged so I removed. One can look at them from data-dog. https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%2C%22log_elb.performance.backend_processing_time%22%2C%22log_duration%22%5D&context_event=AQAAAWl631PIvQdt4wAAAABBV2w2MzJLLVNKc1F4SURrXzRKVg&event&from_ts=1562923610831&index=main&live=true&messageDisplay=expanded-md&query=%22batch-disable%3A+true%22&saved_view&stream_sort=desc&to_ts=1562927210831

**Comment by mfenner** [comment]
If this is from the application, then I am confused. There you are only measuring the rendering to JSON, not the overhead of additional queries.

**Comment by mfenner** [comment]
But if that is too much effort, we can wrap it up, concluding that there is a performance benefit from batch loading.

**Comment by mfenner** [comment]
### No includes 1231.418 ms (mean)
`ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.datacite.org/events?doi=10.6084%2Fm9.figshare.1407_api_024`

### Batch-loading 2553.725 ms (mean)
`ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.datacite.org/events?doi=10.6084%2Fm9.figshare.1407_api_024&include=dois`

### No batch-loading 850.751 ms (mean)
`ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.datacite.org/events?doi=10.6084%2Fm9.figshare.1407_api_024&batchdisable=true&include=dois`

Confusing...

**Comment by kjgarza** [comment]
that DOI doesn't seem to have metadata in production(10.6084%2Fm9.figshare.1407_api_024) . I ran that benchmark in stage. 


I did the benchmark with AB before but my numbers looked very similar

 ab -n20 -H "Accept:application/vnd.api+json; version=2" https://api.datacite.org/events\?include\=dois\&batchdisable\=true

ab -n20 -H "Accept:application/vnd.api+json; version=2" https://api.datacite.org/events\?include\=dois

 ab -n20 -H "Accept:application/vnd.api+json; version=2" https://api.datacite.org/events



| n=20 (no concurrency) |                   |              |             |
|-----------------------|-------------------|--------------|-------------|
|                       | /events           |              |             |
|                       | Batchload enabled | No Batchload | No includes |
| median                | 13075 ms          | 14083 ms     | 13972       |
| Slowest resp          | 19004 ms          | 18744 ms     | 21631       |

**Comment by kjgarza** [comment]
10.15468/6e8nje its a production DOI, it looks more consisntent


### No includes 1240 ms (mean)
`ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.datacite.org/events\?doi\=10.15468/6e8nje`

### Batch-loading 2920 ms (mean)
`ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.datacite.org/events\?doi\=10.15468/6e8nje\&include\=dois`

### No batch-loading 3184 ms (mean)
`ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.datacite.org/events\?doi\=10.15468/6e8nje\&batchdisable\=true\&include\=dois`

**Comment by mfenner** [comment]
I like the approach of loading all DOIs with metadata in the controller first, rather than via the serializer. https://github.com/datacite/lupo/compare/aab41e667026...cea186a1b0b4

But I don't understand why we need `batch-loader` for this, as we are calling the DOIs index only in one place.

**Comment by kjgarza** [comment]
That's is actually a good point. Because we are batching over the whole set of dois. 

Probably I didn't think about it in that way. I wanted to move away from making multiple calls. Batching over each event_id was certainly makes multiple calls. 

I guess a better comparison for performance would be `batching over individual events` (as on Friday) vs `loading all DOIs with metadata in the controller first and use find_by_id`.  As seening, if batching is actually faster. What do you think?

**Comment by mfenner** [comment]
Please don't use batch_loader if you are only loading DOIs once.

**Comment by kjgarza** [comment]
In this benchmark, I am comparing three different approaches to get the metadata: 

A. Batch on each event, 
B. Get all the metadata for all DOIs at once (in the controller)
C. Get DOI metadata by event (as it was implemented before)

I added a row comparing each approach to the baseline (no includes).

examples used: 
- `10.23705/1111111` with 40 events with 25 DOI included
- `10.21373/exwp2m` with 404 events with 25 DOI included

See the table below. Approach (A) and (B) seem to be very similar in terms of speed but definitely an improvement in comparison to the old approach. (A) however, does perform better in the cases I looked into. 


Different calls used: 

```

 ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.test.datacite.org/events\?doi\=10.21373/exwp2m\&include\=dois\&batchload\=singlecall-doi 

ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.test.datacite.org/events\?doi\=10.21373/exwp2m\&include\=dois\&batchload\=batchload-doi 

ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.test.datacite.org/events\?doi\=10.21373/exwp2m\&include\=dois 

ab -n 5 -H "Accept: application/vnd.api+json; version=2" https://api.test.datacite.org/events\?doi\=10.21373/exwp2m 

```




| /events?source-id=datacite-related |                              |                |                  |                   |
|------------------------------------|------------------------------|----------------|------------------|-------------------|
|                                    | No Dois                      | Batch on Event | Get DOIS at once | Get DOIS by event |
| Mean                               | 1617                         | 2051           | 2514             | 2700              |
| Difference                         | 0                            | 434            | 897              | 1083              |
| Compared to the baseline %         |                              | -26.84         | -55.47           | -66.98            |
|                                    |                              |                |                  |                   |
|                                    | /events?doi=10.21373/exwp2m& |                |                  |                   |
|                                    | No Dois                      | Batch on Event | Get DOIS at once | Get DOIS by event |
| Mean                               | 901                          | 1301           | 1244             | 1624              |
| Difference                         | 0                            | 400            | 343              | 723               |
| Compared to the baseline %         |                              | -44.40         | -38.07           | -80.24            |
|                                    |                              |                |                  |                   |
|                                    | /events?doi=10.23705/1111111 |                |                  |                   |
|                                    | No Dois                      | Batch on Event | Get DOIS at once | Get DOIS by event |
| Mean                               | 809                          | 1045           | 1265             | 1495              |
| Difference                         | 0                            | 236            | 456              | 686               |
| Compared to the baseline %         |                              | -29.17         | -56.37           | -84.80            |

**Comment by kjgarza** [comment]
merged in https://github.com/datacite/lupo/commit/b282965fb7744392d9ff4c7344739f600aba1096
