### ISSUE TITLE
Stop using _id for the cursor navigation in our ES searches

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#307]
Based on documentation here 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

To look into changing the sort that we're using for our search_after cursor.
Currently we use _id but this has potential problems as described in the documentation.

Suggested route is to use
Created timestamp - To ensure order of results
Plus a unique identifier for tie-break resolution. This should have 'doc_values' enabled.

This may be related to the issues under #237

**Comment by mfenner** [comment]
Closed via #308.
