### ISSUE TITLE
Total pages in API count is wrong

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#310]
When looking at the total pages count for number of records using cursor based navigation it reports an incorrect value that doesn't match up with the page[size] being used.

We may need to consider removing totalPages entirely if we are using cursor based navigation as cursor allows us to keep going in a set but doesn't necessarily reflect an accurate number.

**Comment by mfenner** [comment]
Agree. We shouldn't show `totalPages` when using cursor-based pagination.
