### ISSUE TITLE
DOI view has two list for the different list of citations

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#312]
Changes for the list:

- Separate results list in two: "references" and citations. That is:
   - citations: All events where the *relation_type_id* is `passive` and the DOI in the landing page is in ins the **subj** of the event AND all All events where the *relation_type_id* is `active` and the DOI in the landing page is in the **object** of the event.
   - references: All events where the *relation_type_id* is `passive` and the DOI in the landing page is in ins the **object** of the event AND all All events where the *relation_type_id* is `active` and the DOI in the landing page is in the **subject** of the event.

Separation of relationt-ypes in the list:

 ACTIVE_RELATION_TYPES = [
    "cites", 
    "compiles", 
    "documents", 
    "has-metadata", 
    "is-supplement-to", 
    "is-derived-from",
    "references", 
    "reviews", 
    "requires", 
    "describes"
  ]
  
  PASSIVE_RELATION_TYPES = [
    "is-cited-by",
    "is-compiled-by",
    "is-documented-by",
    "is-metadata-for",
    "is-supplemented-by",
    "is-source-of",
    "is-referenced-by",
    "is-reviewed-by",
    "is-required-by",
    "is-described-by"
  ]

TODO:

- [ ] New filter for search results in LUPO
- [ ] Add secondary list.
- [ ] Add summary of relation types at the top of each list

**Comment by kjgarza** [comment]
Open questions: 

- [ ] to decided list names. 
   - PROPOSAL: Citations and References
- [ ] to decide relation types in each list (proposal above)
- [ ] to decide mockup list
   - PROPOSAL: to separate Lists with Tabs with their own pagination.
- [ ] to decide whether the summary of relation types is static of dynamic (filters).
   - PROPOSAL: static

**Comment by mfenner** [comment]
I am not sure we can do that. For me the decision is not based on the relation type, but on the provenance.

**Comment by mfenner** [comment]
And don't use `Citations` and `References`, that is confusing. These terms have specific meaning.

**Comment by daslerr** [comment]
In the July 18 product meeting, we decided not to pursue breaking the list into two lists. We will keep it as one list. The to-do item about adding a summary has been moved to https://github.com/crosscite/doi-metadata-search/issues/143.
