### ISSUE TITLE
New citation chart

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#313]
Changes for citation chart:

- Binned by newest year of the nodes in the events
- Only with counts for `things that happened to this item`. That is:
   - All events where the *relation_type_id* is `passive` and the DOI in the landing page is in ins the *subj* of the event AND all All events where the *relation_type_id* is `active` and the DOI in the landing page is in the *object* of the event.

Separation of relationt-ypes:

 ACTIVE_RELATION_TYPES = [
    "cites", 
    "compiles", 
    "documents", 
    "has-metadata", 
    "is-supplement-to", 
    "is-derived-from",
    "references", 
    "reviews", 
    "requires", 
    "describes"
  ]
  
  PASSIVE_RELATION_TYPES = [
    "is-cited-by",
    "is-compiled-by",
    "is-documented-by",
    "is-metadata-for",
    "is-supplemented-by",
    "is-source-of",
    "is-referenced-by",
    "is-reviewed-by",
    "is-required-by",
    "is-described-by"
  ]

TODO:

- [ ] New aggregations for counter and time distribution in LUPO
- [ ] Changes in the controller in LUPO
- [ ] Adapt  API helper in doi-metadata-search

**Comment by daslerr** [comment]
Per discussion in product meeting on July 18, we're opting not to separate the counts into passive and active after all. We'll rely on the deduplication in https://github.com/datacite/lupo/issues/314. 

The citations should still be binned according to the most recent year in the pair.

**Comment by kjgarza** [comment]
There are two approaches for binning the citations by the latter year : binning on the API or binning in the Client.

**Binning in the API**. Seems the best approach as we can be done faster in the elasticsearch index using aggregation functionality. But requires all the data needed to be in the same index, that is the events index. Therefore we need publication_date of the DOIs in the event to be present in the events index. Currently, that is not the case for all DOIs. 

The main issue is that we would need to reindex the events index and include the publication_date of both nodes under the subj and obj information. See https://github.com/datacite/lupo/blob/83786f7ab4b0a3cc2cd9fa9c5a41e6a56fddd84f/app/models/event.rb#L98 

NOTE: it was thought that we could use `occurred_at` timestamp; however, that is not the same as the lastest publication date. `occured_at` uses the `updated` date of the `doi` that generated the event (see https://github.com/datacite/levriero/blob/3dd1814f52fbe5463c5f89450cbc561ce1281a53/app/models/related_identifier.rb#L98). The latter means that `occured_at` is not related to the publication_date of the `dataset,` but it is related to the date of the last change of the `doi` metadata when related identifiers were provided. 

**Binning in the Client**. Using the client would require to obtain all the doi metadata and events and merge and create a time distribution of the client-side. The main disadvantage here is that one would need to paginate through the doi and events to combine them before creating the time distribution for the chart. 


A third approach, what if `occurred_at` is wrong?. In a third approach, we could change how we are generating the `occurred_at` values, that is changing from `updated` to `publication_date.`  This change would assume that the DOI creating the Event is always the one with the latest publication_date.  I am unsure this assumption would always be correct. Anyway, if we follow this approach, we would need not only to reindex the whole /events index but to modify all the events to reflect the change. 

@mfenner, I think "binning of the API" seems a more sensible approach. There are advantages:   
- anybody would be able to obtain the information from API, 
- We do not have to add a bunch of code in the client.

**Comment by mfenner** [comment]
I don't understand what you say about `occurred_at`. It is whatever we want it to be and the name implies that this is when the citation happens.

**Comment by mfenner** [comment]
At this point in the development of the citations functionality, I would implement whatever is the least amount of work, which seems to be in the client.

**Comment by kjgarza** [comment]
added citation binning by latest year in https://github.com/datacite/lupo/pull/330
