### ISSUE TITLE
Disabling Active checkbox in Client does not make client inactive

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#323]
- Investigate what's the current behavior for when active is un/checked.
- add/modify behavior to disable a client at will

**Comment by richardhallett** [comment]
When you mark a client (or now repository) as inactive this :
Changes state in database
Message shown as inactive within sources like fabrica.
API Returns that repos is not active.

It does appear you can still register/update DOI's with an inactive account, is this what the bug is about? should it deny? This might be less a bug than a feature, depending how we want to this to work.
Thoughts?

**Comment by kjgarza** [comment]
> It does appear you can still register/update DOI's with an inactive account, is this what the bug is about?

yes. This came out when ETHZ was hammering our API and we couldn't disable their account, so we changed their password to stop them.

**Comment by richardhallett** [comment]
I looked into this and I believe the logic we need to do is deny access to DOI abilities when the account is inactive.
Looked into this and I believe something along the lines of
cannot [:create], Doi, client: { is_active: 0 } within ability.rb - However this does not appear to work exactly as expected. Needs further investigation.

**Comment by kjgarza** [comment]
here its the incident https://datacite.atlassian.net/wiki/spaces/TEC/pages/970915841/Heavy+usage+across+Services+24-07-19 that originated this issue

**Comment by richardhallett** [comment]
Do not close, needs investigation to confirm current behaviour.

**Comment by mfenner** [comment]
Fixed this in `lupo` API and `bracco` frontend. A repository where the active state is unchecked, should:

Not allow the creation of new DOIs:

![Bildschirmfoto 2021-01-19 um 19.11.21.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/455852e6-f0b9-4a16-992e-255301c2b550)

Not allow updates of existing DOIs:

![Bildschirmfoto 2021-01-19 um 19.12.52.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/a29b5fc7-585a-4094-8b2c-c9d505a1800e)

Not allow addition of prefixes:

![Bildschirmfoto 2021-01-19 um 19.13.48.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/c63e2b1c-bf44-4703-bdea-9bac622a20eb)

Not allow Repository transfer:
![Bildschirmfoto 2021-01-19 um 19.15.03.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/dfcdf1d2-3e4b-434b-b76e-026db8cd939c)

**Comment by svogt0511** [comment]
I tested this in the staging environment (at https://doi.stage.datacite.org/repositories/datacite.datacite/dois). I checked for:

- The repository is marked as 'not active'/active (no designation) as appropriate.
- If the repository is inactive: 
  - DOIs cannot be created, modified or transferred. (The links in the upper left for these functions are removed.)
  - Prefixes cannot be created.  However, there is a way to remove (delete?) them. (Click on a specific prefix and there is a button to 'remove prefix'.)
- If the repository is active:
  - DOIs can be created, modified and transferred.  (The links are there.). I created and modified a DOI but did not do a transfer.
  - Prefixes cannot be created, but can be removed.

It seems that there is no way to create prefixes regardless of the repository state.  I think this was discussed at the meeting earlier today.

Also it seems that prefixes cannot be created regardless of repository state, but they can be remove regardless of repository state.  I did not try removing one.
