### ISSUE TITLE
Version field missing in DOI content-negotation for DataCite XML

### ISSUE THREAD

**Issue by augustfly** [datacite/lupo#354]
Hi, we are fairly confused as to where this error should be reported; there didn't seem to be a correct crosscite repo to ping.  We are happy to be redirected to the correct repository/project.

The following calls to doi.org/crosscite and directly to datacite produce inconsistent metadata. 

```
curl -L -H "Accept: application/vnd.datacite.datacite+xml;q=1" https://doi.org/10.5281/zenodo.28518
```

```
curl https://api.datacite.org/dois/application/vnd.datacite.datacite+xml/10.5281/zenodo.28518
```

The doi.org record is wrong: the version field is malformed/missing. 

While we like the better structured creator fields provided by crosscite(?), the destruction of the version tag is really problematic for our project (asclepias/asclepias-broker).

thanks

**Comment by mfenner** [comment]
@augustfly thanks for reporting, and this repo is fine. The code for content-negotiation service behind doi.org, or directly available via data.crosscite.org is available at https://github.com/crosscite/content-negotiation.

I renamed the issue to what I think better reflects the problem, and will fix this.

**Comment by mfenner** [comment]
@augustfly this took much longer than anticipated, but is finally fixed.
