### ISSUE TITLE
graphql endpoint send Internal Server Error

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#427]
### Expected Behaviour

https://api.datacite.org/graphql
should sent you to graphql query interface

### Current Behaviour
https://api.datacite.org/graphql
> Internal Server Error

### Steps to Reproduce

1. https://api.datacite.org/graphql

### Context (Environment)

Graphql federation service seems to be done since Monday
"Expected undefined to be a GraphQL schema"

https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%2C%22log_elb.performance.backend_processing_time%22%2C%22log_duration%22%5D&context_event=AQAAAWl631PIvQdt4wAAAABBV2w2MzJLLVNKc1F4SURrXzRKVg&from_ts=1579598941295&index=main&live=true&messageDisplay=inline&query=%22Expected+undefined+to+be+a+GraphQL+schema%22&stream_sort=desc&to_ts=1582190941295

**Comment by mfenner** [comment]
Fixed via https://github.com/datacite/lupo/issues/428
