### ISSUE TITLE
Pagination fails after 3 million records

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#453]
### Expected Behaviour

one should be able to paginate the whole dois index using cursor pagination.

### Current Behaviour

Pagination fails after 3 million records

Case A: 

https://api.datacite.org/dois?page%5Bcursor%5D=MTQ3MDg5Nzc1MDAwMCwxMC4xNTQ2OC9scHNmbnQ&page%5Bsize%5D=1000

after key: 1470897750000,  10.15468/lpsfnt

Case B: 

The API call allowed 1000 records per batch. The speed is normal.

However, after I downloaded 3M of the total 24M records, the following URL always give me timeout errors. This URL was generated 6pm, 3/10/2020. Has it been expired?

 

https://api.datacite.org/dois?page%5Bcursor%5D=MTQzMTUzNjQxNjAwMCwxMC4xNTQ2OC9panA4cDk&page%5Bsize%5D=1000

after key: 1431536416000, 10.15468/ijp8p9

### Steps to Reproduce

1. Use cursor base pagination to transverse the DOIs index

### Context (Environment)

Both failures are when harvesting GBIF Dois. It's unclear if that is related. 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1fwxv)

**Comment by yubarry** [comment]
I got "500 Internal Server Error" error with the following cursor after downloading 6,134,000 records from DataCite.

https://api.datacite.org/dois?page[cursor]=MTQ3MDg4NTE0ODAwMCwxMC42MDczL3Bhc3RhLzA4ZTljMGViZjM3MjcxMWRiYWM3NDk0MTZhNjA2NDVi&page%5Bsize%5D=1000&page[size]=1000

**Comment by kjgarza** [comment]
this to be closed and to be addressed as part https://github.com/datacite/datacite/issues/926
