### ISSUE TITLE
Media retrieval via API raises database error

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#466]
GET to 
https://api.datacite.org/dois/10.22002/D1.1278/media
OR via MDS  https://mds.datacite.org/media/10.22002/D1.1278

Both return:

undefined method `page' for #<Media::ActiveRecord_AssociationRelation:0x0000561f0ad9cb58>"

**Comment by mfenner** [comment]
Duplicate of datacite/poodle#33.
