### ISSUE TITLE
Connect logs with Datadog traces

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#470]
Connect logs to traces as per instructions at https://docs.datadoghq.com/tracing/connect_logs_and_traces/ruby/?tab=lograge.

**Comment by sarala** [comment]
@mfenner Is this meant to connect AppAnalytics to logs as well? Is this. change going to production soon?

**Comment by mfenner** [comment]
That is the plan, but it needs some tweaks.

**Comment by sarala** [comment]
Okay, I'll leave it with you as I don't know what tweaks are needed. Let me know when it is in production so I can see the logs via app analytics.
