### ISSUE TITLE
Expand API to dois endpoint to include provider relationship

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#516]
To support being able to determine who a doi belongs to beyond the client to add provider, this is needed by https://github.com/datacite/viringo/issues/53 which in turn is related to the work of splitting out ids from accounts.

This should preferably be a non breaking API change, which should be possibly if we are just adding in additional relationship as per JSON:API spec.

**Comment by mfenner** [comment]
@richardhallett can you clarify what information you need for Viringo? Is it only the provider ID? Or also other information? The provider ID is included in the information from the client: https://api.datacite.org/dois?include=client

**Comment by mfenner** [comment]
I am reluctant to do any changes that potentially slow down the performance of the dois API endpoint.

**Comment by richardhallett** [comment]
As per datacite/viringo#53 I need for each DOI who the client and provider is. This is needed to show the "sets" in relation to each DOI e.g. see setSpecs on doi records: https://oai.test.datacite.org/oai?verb=ListRecords&metadataPrefix=oai_dc

It may be possible to use ?include=client I guess, as I could build a hash map and look it up per DOI.

https://api.datacite.org/dois?include=client this will always include all clients for all DOI's that are returned in the results correct?

**Comment by mfenner** [comment]
Yes, https://api.datacite.org/dois?include=client returns all clients (with provider_id) from the result set.

**Comment by richardhallett** [comment]
This was solved as part of https://github.com/datacite/viringo/issues/53 by returning provider in response of relations when detail is true.
