### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/users/xxx"

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#543]
This error is appearing in our logs, however for every case of the user, it does correctly return the user data and does not cause a route error.

i.e. https://api.datacite.org/users/0000-0002-4595-230X

Works as expected, despite appearing in logs as having a route error.

## Hypothesis
This data should be coming from the profiles (volpino) service, this is handled by the load balancer which targets based on /users*

However I am wondering if another internal service is not going via the load balancer and thus triggering an unknown route.

**Comment by mfenner** [comment]
This has been fixed.
