### ISSUE TITLE
Citation styles for text/x-bibliography returning html

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#572]
A user reported that they are now receiving html in their citations when requesting via content negotation see:

`
curl https://data.crosscite.org/10.2312/GFZ.b103-20035 -H 'Accept: text/x-bibliography' -H 'style: apa' -H 'locale: en-US'
`

Returns:
`Strollo, A., Evans, P., Heinloo, A., Hemmleb, S., Hillmann, L., Jäckel, K.-H., Quinteros, J., Saul, J., Zaccarelli, R., Zieke, T., &amp; Tilmann, F. (2020). GEOFON Annual Report 2019. In <i>Scientific Technical Report STR; 20/03</i> (Version 2.2). GFZ German Research Centre for Geosciences. https://doi.org/10.2312/GFZ.B103-20035`

Note the &amp and <i>

@mfenner I think maybe this is related to this, so I'm not sure what implications are for the graphql part.
https://github.com/datacite/lupo/commit/5fc1799b13778b25f5d6052702ff618eaa4e2bd2

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ntzp)

**Comment by mfenner** [comment]
This is intended and has been like this for a while. It is in particular needed for italic, which is rather common.

**Comment by richardhallett** [comment]
But shouldn't the text part imply it is just text and not html?
The user suggested this was different before, so was it broken before and now fixed? How should a user handle the use-case of not receiving html parts?

**Comment by mfenner** [comment]
There is no spec to for example say "I want text or HTML". HTML is the better default, as you can easily go from HTML to text, but not the other way around. I would not say it was broken before and now fixed, but rather say we added a feature :).

An unresolved issue is math in titles and descriptions that requires Mathjax to render, done frequently by Hepdata and other CERN repositories.

**Comment by richardhallett** [comment]
Okay closing as answer is that it should be defaulting to html for formatted styles, answer should be to strip html if required.
