### ISSUE TITLE
Allow update of URL regardless of metadata schema version

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#579]
When attempting to update a URL, if the metadata is an older schema version it can cause a validation error, this can prevent users updating the URL.

This specifically came up when a user was attempting to set the URL via MDS for a schema 2.2 metadata.

Discussed and it was decided it would make more sense to allow updates to URL regardless of the schema version used.

**Comment by mfenner** [comment]
Related to datacite/bracco#439.

**Comment by richardhallett** [comment]
While this might still be an issue it needs to be handled in context of how our APIs work and most likely will compromise a future rework.
It also depends how we handle schema changes in the future, work is currently being discussed around this as part of next schema versions.
