### ISSUE TITLE
UpdateDoiJob should not trigger sending a message to levriero

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#582]
UpdateDoiJob currently updates metadata that are not relevant for Event Data. A DOI update via this job should therefore not trigger `send_message`.

**Comment by kjgarza** [comment]
what about the use case of a member adding a "related Identifier"  to the metadata after the creation of the DOI?. The eventData Agent won't know this update unless the Job is generated, right?

**Comment by mfenner** [comment]
UpdateDoiJob is only used for rake tasks triggered by us, so that should be fine until we have rake tasks that trigger changes in fields relevant for Event Data.

**Comment by mfenner** [comment]
What I will implement is to only trigger `send_message` after DOI update when a field relevant for Event Data is changed, using `saved_change_to_attribute?`. I am thinking the following attributes need to trigger an update in Event Data:

* creators
* related_identifiers
* funding_references

Do I miss anything @kjgarza ? We are currently not extracting nameIdentifiers and affiliationIdentifiers from contributors.
