### ISSUE TITLE
Failed to parse date field [1941-06] with format [strict_date_optional_time||epoch_millis]

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#586]
Need to implement more flexible parsing for `dates`.

See https://github.com/elastic/elasticsearch/issues/47473 for background.

**Comment by richardhallett** [comment]
@mfenner Is this related to a sentry error, do we have a specific example to reproduce?

**Comment by mfenner** [comment]
I regularly see this error in our Datadog logs.
