### ISSUE TITLE
Add "first" to organizations in graphql

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#592]
Required for organisations search to return set list, atm there is no way to set limit of how many is returned as the common parameter "first" is missing.

i.e.

```
query getContentQuery
{
    organizations(first: 25) {
      totalCount
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        node {
          id,
          name
        }
      }
    }
  }
```

**Comment by mfenner** [comment]
The ROR API has a fixed value of 20 results per page, so we currently can't implement `first`.

**Comment by richardhallett** [comment]
Ah okay that makes sense, thanks, just wanted to capture this in case it was an oversight, happy to close.
