### ISSUE TITLE
 filtering citations/references is not working on the graphql API

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#602]
### Current Behaviour

I think filtering citations/references is not working on the graphql API

![image](https://user-images.githubusercontent.com/1092861/90009654-c10cb380-dc9e-11ea-83c2-50511fe8d1b1.png)

### Steps to Reproduce

run this query in stage

```
{
  work(id: "10.4224/crm.2012e.nass-6"){
    citationCount
    citationsOverTime{
      year
      total
    }
    citations(published:"2014"){
			published{
        id
        count
      }
    }
  }
}
```

### Context (Environment)

Stage environment.

**Comment by mfenner** [comment]
Fixed via #636.
