### ISSUE TITLE
Delete Event action doesn't work

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#604]
### Expected Behaviour

Admin should be able of deleting an event

I'm getting 500 it could that authorize_resource has not been correctly declared for the Events model

### Steps to Reproduce

1. step1
2. step2
3. step3
4. step4

### Context (Environment)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o13p)

**Comment by kjgarza** [comment]
```
{
  "errors": [
    {
      "status": "400",
      "title": "undefined method `destroy' for #<Elasticsearch::Model::Response::Result:0x000055b06b9c6d48>"
    }
  ]
}
```

**Comment by mfenner** [comment]
You should load the database record and perform the action on it instead of the Elasticsearch record.
