### ISSUE TITLE
Create DMP type in GraphqL API

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#610]
To add a resource and queries for DMPs

Custom Aggregation for DMPs
> Query would be types.resourceTypeGeneral:Text AND types.resourceType:"Data Management Plan"

https://doi.datacite.org/dois?page=NaN&query=types.resourceTypeGeneral%3AText%20AND%20types.resourceType%3A%22Data%20Management%20Plan%22&resource-type-id=&sort=relevance

Respond to the query:

![carbon (24)](https://user-images.githubusercontent.com/1092861/91168564-21a3e380-e6d6-11ea-9dfe-76b924a5ad2c.png)

Aggregations:

- Datasets. Includes all citations and references of type dataset
- Funders. alias for fundingReferences
- organisations. Includes ror ids in `funderIndetifiers` and in creators.affiliation and contributor.affiliation if (contributor role is HostingInstitution)
- People. Includes all creators and contributors

**Comment by mfenner** [comment]
@kjgarza I would recommend to not change the built-in types used elsewhere, e.g. what you propose with `funders` or `people`.
