### ISSUE TITLE
Support authentication via the GraphQL API

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#622]
Support GraphQL authentication via a JWT sent from the `akita` service. This requires:

* correct CORS permissions of both the gateway (vaestgoetaspets) and API (lupo)
* parsing of the JWT in the API. Return correct response for query below, and error message if something goes wrong
* also optionally return information from a query, not just what is stored in the token

```
{
  me {
    id
    name
    betaTester
  }
}
```

**Comment by kjgarza** [comment]
@mfenner I think I am experiencing problems to mint DOIs in stage related to this change. see below

![image](https://user-images.githubusercontent.com/1092861/92406797-3d2cd680-f139-11ea-99a2-630c50e9979f.png)

**Comment by mfenner** [comment]
This should be fixed once the fix https://github.com/datacite/lupo/commit/4638b70d660caa68f27eee22e359b73e56656817 is deployed.
