### ISSUE TITLE
Support queries by ROR ID for contributors with contributorType "hostingInstitution"

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#628]
# Request

To include contributors affiliation with contributorType "hostingInstituion" to the affiliation_id

https://github.com/datacite/lupo/blob/a9056c5/app/models/doi.rb#L1677

This affiliation seems to be missing from the graphql queries

**Comment by mfenner** [comment]
There are five places where a ROR ID can appear in DataCite metadata:

* creator affiliationIdentifier
* creator nameIdentifier
* contributor affiliationIdentifier
* contributor nameIdenfifier
* fundingReferences funderIdentifier

The use or ROR IDs as funderIdentifier is still very uncommon.

When we use a contributor with contributorRole `HostingInstitution`, we can put the ROR ID in the nameIdentifier field, and the changes in this issue add support for that. But this is not an affiliation, so the query is for `organizationId` and not `affiliationId` in GraphQL or the REST API.

**Comment by kjgarza** [comment]
@mfenner I am not sure this issue is closed.

Look at this DOI https://api.datacite.org/dois/10.48321/D1H59R. it has : 

```
{
name: "California Digital Library",
nameType: "Organizational",
givenName: null,
familyName: null,
affiliation: [ ],
contributorType: "HostingInstitution",
nameIdentifiers: [
{
schemeUri: "https://ror.org",
nameIdentifier: "https://ror.org/03yrm5c26",
nameIdentifierScheme: "ROR"
}
]
}
```

and yet a call for that OrganisationID in the GraphQL API won't result to that DOI/DMP:

![image](https://user-images.githubusercontent.com/1092861/93450055-c8466300-f8d5-11ea-9375-355be40805e8.png)
