### ISSUE TITLE
Filter DMPs by contributorType of Contributor Organization.

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#632]
**As a** Admin
**I want** to be able to get all the DMPs that an Organisation Produced or is Hosting
**So that** I can get only filter other DMPs in which Organisation is not the main contributor.

When showing DMPs of an **organization** one should be able to filter the DMPs in which the Organization is HostingInstitution or the Producer of the DMP. 

## Technical proposal

When searching for DMP  filter by (contributorType)
- Producer organization. https://support.datacite.org/docs/schema-optional-properties-v43#7a-contributortype
- HostingInstitution organization. https://support.datacite.org/docs/schema-optional-properties-v43#7a-contributortype

example: https://api.datacite.org/dois/10.48321/D1H59R

Maybe something like:
```
{
 dataManagementPlans(contributorType:"HostingInstitution") {
     id
    contributors {
      id
      name
      affiliation{
        id
      }
    }  
  }
}
```

### General

- [ ] [Write a feature spec to test frontend and backend change altogether](MR link if it already exists)
- [ ] [Remove the feature flag and update documentation](MR link if it already exists) # i.e. publish the feature

**Comment by mfenner** [comment]
This is already supported in the GraphQL API:

```
{
 dataManagementPlans {
     id
    contributors(contributorType:"HostingInstitution") {
      id
      name
      affiliation{
        id
      }
    }  
  }
}
```

**Comment by kjgarza** [comment]
@mfenner that's filter for contributors. This Issue is about a filter for DMPs with certain contributor.

**Comment by mfenner** [comment]
I am not sure filtering by DMPs with a certain contributor is a use case for the GraphQL API beyond DMPs. With the number of DMPs as low as they are now, I prefer to get all DMPs that include a certain ROR ID in the contributor metadata, and filter in the Jupyter notebook. Also, what are the contributor types for organizations that you want to filter out and that are used with any frequency?

My vision for the GraphQL API is to do what is needed, but keep it as generic as possible. Easier to learn and maintain.

**Comment by kjgarza** [comment]
> I am not sure filtering by DMPs with a certain contributor is a use case for the GraphQL API beyond DMPs. 
Well this request is just coming from the maDMP **Grant** Feedback

> I prefer to get all DMPs that include a certain ROR ID in the contributor metadata, and filter in the Jupyter notebook.
wouldn't the main problem using that approach be that users of the GraphQL API will need to `paginate` until they get all the DMPs and then filter on the client?

> what are the contributor types for organizations that you want to filter out and that are used with any frequency?
Maria and Bryan said that **Producer** and **HostingInstitution** would be good for it. https://support.datacite.org/docs/schema-optional-properties-v43#7a-contributortype

**Comment by mfenner** [comment]
With less than 200 DOIs for DMPs pagination is not an issue yet. We shouldn't overengineer, before the numbers are high enough so that we need it. Also, we are at the end of development work for this, not at the beginning.

With filter out, I mean what contributor types for organizations we need to remove.

**Comment by mfenner** [comment]
Please write a few lines of Python to address this.

**Comment by mfenner** [comment]
I have implemented a fix to show all contributors when no filtering by contributor type is present.

**Comment by mfenner** [comment]
Closes #630.

**Comment by kjgarza** [comment]
```  works(query: "contributors.contributorType:HostingInstitution OR contributors.contributorType:DataManager", hasOrganization: true) {
```

@mfenner part I think still needs to be implemented for the **Organisation** Type in https://github.com/datacite/lupo/blob/831f22c/app/graphql/types/organization_type.rb#L86

As it stands it will only work when making a call for the DMP resource and but for the DMP resources within an Organisation. I can add it if that's ok?

**Comment by mfenner** [comment]
I can add that to `organizationType` today.

**Comment by mfenner** [comment]
I found a bug how the nameIdentifier for an organization in the DOI metadata is looked up. I fixed this and added a test that is now passing. Should be in stage in 30 min, in production no later than tomorrow morning.
