### ISSUE TITLE
Metadata transformation problem for alternateIdentifiers

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#641]
this could be  an API problem, like the API is not converting alternativeIDentifiers (XML) to identifiers (JSON) the metadata in json doesn't show them either https://api.datacite.org/dois/10.24397/pangloss-0000008

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o3px)

**Comment by kjgarza** [comment]
For context, Bolognese Transformation is working correctly with this metadata file

**Comment by kjgarza** [comment]
The problem is related to way we replace the `alternatedIdentifiers` with `identifiers`.  

When sending XML the identifier field is `blank` but is not `nil` therefore the API takes it (see [lupo:L147](https://github.com/datacite/lupo/blob/a85b412/app/controllers/datacite_dois_controller.rb#L714) ) as if the request included and empty value.  This condition is not necessarily wrong as API might want to replace a value with `blank`.

**Comment by richardhallett** [comment]
I can reproduce this.

1. Create a XML document with alternateIdentifiers listed
2. Do a GET from https://api.stage.datacite.org/dois/thedoi
3. Note the response does not contain the alternateIdentifiers in either identifiers or alternateIdentifiers field.
4. Look at XML note it does contain the alternateIdentifiers

Example XML
```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI">10.24413/DMVJ-JS47</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Hallett, Richard</creatorName>
      <givenName>Richard</givenName>
      <familyName>Hallett</familyName>
    </creator>
  </creators>
  <titles>
    <title>Title</title>
  </titles>
  <publisher>Acme Inc</publisher>
  <publicationYear>2020</publicationYear>
  <resourceType resourceTypeGeneral="Audiovisual">MediaObject</resourceType>
  <alternateIdentifiers>
    <alternateIdentifier alternateIdentifierType="URL">https://schema.datacite.org/meta/kernel-4.3/example/datacite-example-full-v4.3.xml</alternateIdentifier>
  </alternateIdentifiers>
  <sizes/>
  <formats/>
  <version/>
</resource>
```

**Comment by richardhallett** [comment]
This has now been fixed. The root problem laid in an additional empty param being sent for identifiers when alternateIdentifiers was empty, this caused the version from XML to be overriden.
