### ISSUE TITLE
Correctly show citations and citation counts in GraphQL

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#649]

**Comment by kjgarza** [comment]
For context:

counts are also wrong in the Index look at `citationCount` and `citations.totalCount`

citations.totalCount
https://github.com/datacite/lupo/blob/52c6e7a/app/graphql/connections/hash_connection.rb#L58
https://github.com/datacite/lupo/blob/52c6e7a/app/graphql/types/doi_item.rb#L426

citationCount
https://github.com/datacite/lupo/blob/52c6e7a/app/models/doi.rb#L1409


The difference in the counts is related to that there are differences between the DOI in the Database and the DOI in the Index. for example `10.1139/CJFR-2018-0211` was in the DB table but not in the index. So when one is querying for citations in graphQL the API queries the index. Event if the citations id are correctly collected the counts will be wrong if the citation DOI is not in the DOI index. This can happen when:

(a) the citation DOI has not been imported to our database Or
(b) the citation DOI has not been imported to our DB but indexing didn't happened correctly.

**Comment by mfenner** [comment]
Please put the details in the respective issues. This epic is intended as an overview of all the work related to citations and citation counts, and we should avoid duplication.

**Comment by kjgarza** [comment]
but which tickets is the one that will aim to solve the problem of indexing all the DOIs from Crossref and Datacite (when DOIs are not correctly indexed) ?  I think there is not ticket on this epic about that.

**Comment by mfenner** [comment]
This is part of the work @richardhallett is doing and there are issues for that. This epic focusses on specific bugs.
