### ISSUE TITLE
CitationsCount missing for is-supplement-to relation

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#654]
The doi 10.17632/gw33xrgkm5.1 has a relation of the type IsSupplementTo and that should be counted as a citation.

https://api.datacite.org/dois/10.17632/gw33xrgkm5.1

the graphQL api returns no citations count

![image](https://user-images.githubusercontent.com/1092861/95854967-fcd40000-0d57-11eb-8605-ce3f517781b4.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o5sl)

**Comment by mfenner** [comment]
@kjgarza I suggest to not open an issue for a single DOI, as this is most likely a more fundamental issue. Is this already addressed in an open issue?

**Comment by kjgarza** [comment]
well it sounds to be very similar https://github.com/datacite/lupo/issues/637 but that is closed now

**Comment by mfenner** [comment]
This is a data quality issue that will be addressed via datacite/datacite#1092. Closing this issue.
