### ISSUE TITLE
Long text entered into rights metadata causes an elasticsearch index problem

### ISSUE THREAD

**Issue by richardhallett** [datacite/lupo#663]
If you have a metadata document that includes rights which for example includes long amounts of text (the specific example was the GPL license), when Lupo attempts to index this with ElasticSearch fails with an error, I believe this is due to trying to index on a large piece of text for the field type it is.

We might need to just change the field type for the rights metadata so it indexes better.

**Comment by richardhallett** [comment]
Did this get fixed? Or do we need more information, the sentry issue stopped triggering due to the fact it's a rare example.
Or are we just wanting to perhaps limit rights and say that it isn't supported for ES indexing.

**Comment by mfenner** [comment]
Fixed going forward via https://github.com/datacite/lupo/pull/689 (limiting rights to 2000 characters). Still need to clean up existing metadata records, in particular in PURDUE.HUBZERO.
