### ISSUE TITLE
To hide email addresses when API is accessed unauthenticated

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#685]
## Problem

According to GDPR and our privacy policy we need hide email addresses  from unauthenticated access

"DataCite does not disclose personal data other than as described in the Protection of Information section below." https://datacite.org/privacy.html

## Use cases

- **As a** client **I want** to be able to edit/add email addresses for my profile **So that** keep them up to date
- **As a** user **I want** my multiple emails not to be accessible via the API (or other interfaces) to other entities other than myself (and DataCite Staff)  **So that** so that the API can be compliant with DataCite Privacy policy and GDPR.

### Possible Implementation

potentially it can be filtering the field as in https://github.com/datacite/lupo/blob/d57277113447e4d5a0addd580ea3a87506913bd0/app/serializers/provider_serializer.rb#L179

**Comment by mjbuys** [comment]
@kjgarza @sarala @richardhallett @mfenner we should hide email addresses in all cases - regardless of authentication.

**Comment by mfenner** [comment]
This has been addressed, requiring appropriate authentication and authorization to see email addresses (needed by Fabrica service).
