### ISSUE TITLE
Handle registration not triggered

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#70]
Under some circumstances, a handle registration is not triggered for a new DOI.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c403)

**Comment by richardhallett** [comment]
After investigation this was related to not passing through the current user on create requests and manifesting itself as 401s being returned, a fix has been applied and this should resolve any future registration problems related to authentication.
