### ISSUE TITLE
Option for GraphQL API to return all subject areas

### ISSUE THREAD

**Issue by antonninkov** [datacite/lupo#701]
We would like to have the option of using the GraphQL API to return all the subject areas in the database. Currently, only 10 are returned. For example, in the following GraphQL call, we would like to see any subject areas/fieldsOfScience/disciplines that have datasets published. Right now, only the 10 subject areas with the most datasets are returned. Thanks!

`
{
  datasets {
    totalCount
    fieldsOfScience{
      title
      count
    }
}
}`

**Comment by mfenner** [comment]
@antonninkov would something like this work?

```
{ datasets { 
    totalCount 
    fieldsOfScience(facetCount: 50) { 
      title 
      count
    }
  }
}
```

Where `facetCount` would have a default value of `10`, not breaking the current implementation.

Facets (Elasticsearch aggregations) are a major performance bottleneck, so this expanded result set will take some time. Probably not a problem in a Jupyter notebook, but this change would be noticeable in a web interface with live data.

**Comment by antonninkov** [comment]
Yes, a solution like this would be great. It would also be great if this could similarly be applied to Licenses.

**Comment by mfenner** [comment]
@antonninkov The following now works and should give you what you need:

```
{ datasets(facetCount: 50) {
    totalCount
    fieldsOfScience { 
      title 
      count
    }
  }
}
```

The facet count is provided at the top level, as that was the best way to implement this. This is an optional setting that defaults to 10, and also works for licenses or other facets, e.g. 

```
{ datasets(facetCount: 50) {
    totalCount
    licenses { 
      title 
      count
    }
  }
}
```

The performance is reasonable when using only a single facet like in the examples above. Let me know if that doesn't solve your issue.

**Comment by antonninkov** [comment]
Thanks Martin. Would this all work for "published" variable?

**Comment by mfenner** [comment]
No. That is currently hard-coded somewhere else, as faceting time-series works differently. Currently it is all years starting with 2010 and ending with the current year. I can include that, but maybe you want something else: start year and end year of the facets?
