### ISSUE TITLE
Wrong numbers of DOIs per provider

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#708]
The numbers of DOIs per provider (TODN, 3358) are different than per repository (DK.DTIC, 6651). All DOIs are in the Elasticsearch index.

## Working hypothesis
Some of the DOIs are indexed with another provider, as this happened after a repository transfer.

**Comment by richardhallett** [comment]
This was due to duplications appearing in the "other" index, i.e. DataCite dois appearing there when they shouldnt. These have been removed.
