### ISSUE TITLE
Increase request entity size

### ISSUE THREAD

**Issue by timrobertson100** [datacite/lupo#712]
[GBIF](https://www.gbif.org) are receiving  "413 Request Entity Too Large" from DataCite when creating DOIs.

Our metadata contain relationships to other datasets and are often large as we can link to ~16,000 other datasets. We expect this to continue to grow.

Being able to correctly attribute and link the source datasets is critical to our operations.

Can you please increase this limit (suggest doubling it)?

**Comment by mfenner** [comment]
@timrobertson100 we currently limit the request size to 10 MB via the nginx web server configuration. What is the file size of those DOIs with 16k related identifiers?

I assume you compress those requests with gzip before sending to us.

**Comment by mike-podolskiy90** [comment]
@mfenner the size is about 15 MB

**Comment by mfenner** [comment]
Do you expect this to be good enough for the next 2-3 years? Would increasing the file size limit 20 MB be sufficient? And could you share an example metadata record (ideally via URL) with that size?

**Comment by timrobertson100** [comment]
@mike-podolskiy90 - can you please explore if GBIF are indeed compressing before sending to DataCite?

**Comment by mike-podolskiy90** [comment]
We're not compressing files, so we gonna do that.
@mfenner thank you for the quick reply
Close this.

**Comment by mfenner** [comment]
Excellent, compression should give you a lot of extra mileage for the 10 MB that are currently allowed. Ping us if that is not enough.

**Comment by timrobertson100** [comment]
Will do. Thanks for pointing us in the right direction @mfenner

**Comment by mfenner** [comment]
@timrobertson100 one more question: do you use the MDS API or the REST API? As the MDS API is, in turn, using the REST API, so two layers that each need to decompress and send forward.

**Comment by timrobertson100** [comment]
REST API using our [Java Data Cite client](https://github.com/gbif/datacite-rest-client/blob/master/datacite-rest-client/src/main/java/org/gbif/datacite/rest/client/retrofit/DataCiteRetrofitClient.java)

This implements the parts GBIF need but may  be a good candidate for a more complete Java client. We'd be happy to move it to the DataCite repository if desirable, or see it forked.

**Comment by mfenner** [comment]
Thanks Tim. We should have a discussion about how to make existing DataCite client applications more visible.

**Comment by mike-podolskiy90** [comment]
@mfenner Sorry but I did not manage to perform a request with compressed data. And I also did not find a documentation how to do that. Could you provide me with a curl + payload example please?

**Comment by mfenner** [comment]
It is basic nginx compression functionality, nothing specific to our DOI registration service. Try this in the header:

```
"Content-Type" : "application/gzip",
"Content-Encoding" : "gzip",
"Authorization": "Bearer " + BEARER
```

**Comment by mike-podolskiy90** [comment]
That's pretty the same I tried, but got "You need to provide a payload following the JSONAPI spec"

```
POST https://api.test.datacite.org/dois
Content-Type: application/gzip
Authorization: Basic user password
Content-Encoding: gzip
Cache-Control: no-cache
```
[request-3.json.gz](https://github.com/datacite/lupo/files/5921302/request-3.json.gz)

Regular unzipped is working fine

**Comment by mfenner** [comment]
Let me try your file tomorrow, it is getting late here.

**Comment by mike-podolskiy90** [comment]
of course, sorry for disturbing

**Comment by mfenner** [comment]
@timrobertson100 this needs a bit more end on our side by @svogt0511, but should be ready this week.

**Comment by timrobertson100** [comment]
Thanks @mfenner and all involved for investigating. We saw the PR so I opened this again just for clarity.

Once fixed, GBIF will update a lot of historical DOI metadata as we've been handling this by stripping all the citations from the data we POST. If that is concerning for e.g. load reasons please let us know and we can coordinate the updates.

**Comment by mfenner** [comment]
More metadata is always good :) We should investigate whether we can optimize the handling of metadata records with e.g. > 10,000 relatedIdentifier entries.

**Comment by svogt0511** [comment]
We have an update coming for adding gzipped content via the REST API. 

Suzanne Vogt | Application Developer | DataCite
E: ***@***.*** | ORCID
W: datacite.org | Blog | Twitter | LinkedIn
Support Desk | Support Site | PID Forum

--- original message ---
On May 27, 2021, 10:18 AM EDT ***@***.*** wrote:



I am also having problems POSTing gzipped content to the REST API. I am using a different jersey based client for the Catalogue of Life that uses pure JSON without the xml field. It all works fine when I disable the gzip request compression. With the compression I get a 400 bad request error

A problematic example conversation:

>> POST /dois HTTP/1.1 
>> Accept: application/json 
>> Authorization: Basic SOME_BASIC_CREDS== 
>> Content-Type: application/json 
>> Content-Encoding: gzip 
>> User-Agent: COLTest 
>> Content-Length: 399 
>> Host: api.test.datacite.org 
>> Connection: Keep-Alive 
>> Accept-Encoding: gzip,deflate 
>> "[\r][\n]" 
>> ***@***.***[0xfd]+[0xc8]g[0xf6][0x83][0xee][0xb6]"{[0xcb]6j[0xb4][0x97][0xa6]jzi[0xaa][0x1c][0xcc][0xe0][0x1]K,[0x83]fL[0xb6][0xe9][0x8a][0xff]^[0xf]l*[0xa2][0xaa][0x97][0xa8]H [0xf3][0x9e][0xfd][0xf0][0xf3][0x98]3[0x94]([0x8][0xbb]3[0xa0][0x88][0xe7][0xa2][0x17][\n]" 
>> "[0xf1][0xad]t[0xc];[0xc8][0xd6][0xcb]|[0xfd]a[0x93][0xad]b[0x92]a[0xe5][0xc8]?[0xb1]![0x96]E[0xb1][0xcd]r[0xdc][0xbc][0xc7]E[0x91][0xe5][0xdb][0xc5][0xb6][0xc8][0xb6][0x1a][0x91]U<[0xb7][0x16]7[0xf9]U[0xf9].[0x87][0x14][0x8c]'[0x14][0xe7]U[0xf3][0xc7][0x19]Z<[0x92][0xaa][0xee][0xb1][0xad][0x92][0xbd]s[0xc7]$F[0x9a][0x14][0xf1]o[0xcf]][0xe4][0xee]|[0x85]-[0xff]Ba[0xd7]b[0x3]Cz[0x9e][0xb3]_[0xc8][0x87][0x11]O[0xa1][0xe2]'j?O[0x82][0xf7]B[0x16][[0x5]-[0x1e][0xb9]y[0xbe][0xa0][0xf]'[0xe2][0x17][0xf5]CI[0xad][0xb0]e[0xf2]�[0x1a][0x99]C[0xb0][0xd6]k[0xf1][0xea][0x91][0xfd]Uyoj[0x1a][0x85][0xef][0xbe]~<[0xdc][0xc0][0xf0]8<[0xa6] ,[\r]M[0xee][0xc6]P[0xe9][0xeb]&[0xb8]$t[0x1e]M[0x9d]<[0xa0]G[0xa9][0xfb] [0x1e]![0xa6]w}[0xd1]p[0xa8][0xc7]o[0xde][0xee][0xf][0x9f][0xe0][0x2][0x99][0xd1][0xf0]wB%[0xb2][0xab]<Wau<[0x9e][0x84][0xa7][0xe0]zo[0xc6][0x11][0xdc]RK^[0xed][0xef][0xe0]F[0xf]$[0x90]h[0xfd][0x9c][0x9f][0x11]C[\n]" 
>> ***@***.******@***.***Bo'[0xec][0x8d][0xaa]:[0x11].[0xff][0xcb]R[0xcb]4[0x10][0xfd]G[0x2][0xc][0xc3]o[0x87]?[0xb8][0x1f]C[0x3][0x0][0x0]" 

<< "HTTP/1.1 400 Bad Request[\r][\n]" 
<< "Date: Thu, 27 May 2021 14:12:18 GMT[\r][\n]" 
<< "Content-Type: application/json; charset=UTF-8[\r][\n]" 
<< "Content-Length: 36[\r][\n]" 
<< "Connection: keep-alive[\r][\n]" 
<< "Status: 400 Bad Request[\r][\n]" 
<< "Vary: Origin[\r][\n]" 
<< "X-Request-Id: 677cac14-2c58-410a-941e-22da2c5c649e[\r][\n]" 
<< "X-Runtime: 0.458357[\r][\n]" 
<< "X-Rack-CORS: miss; no-origin[\r][\n]" 
<< "X-Powered-By: Phusion Passenger(R) 6.0.8[\r][\n]" 
<< "Server: nginx/1.14.0 + Phusion Passenger(R) 6.0.8[\r][\n]" 
<< "[\r][\n]" 
<< "{"status":400,"error":"Bad Request"}" 

I will leave compression off for now.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by svogt0511** [comment]
Just pushed the fix for this to production.  I am closing this issue.
