### ISSUE TITLE
Citations do not always properly show up in DataCite Commons

### ISSUE THREAD

**Issue by mfenner** [datacite/lupo#734]
Example:

```
{
  "data": {
    "id": "add563dc-cefe-4519-89bd-1c78e2cbad7a",
    "type": "events",
    "attributes": {
      "subj-id": "https://doi.org/10.17863/cam.298",
      "obj-id": "https://doi.org/10.1162/coli_a_00263",
      "source-id": "datacite-crossref",
      "relation-type-id": "is-supplement-to",
      "total": 1,
      "message-action": "create",
      "source-token": "28276d12-b320-41ba-9272-bb0adc3466ff",
      "license": "https://creativecommons.org/publicdomain/zero/1.0/",
      "occurred-at": "2021-04-28T14:01:14.000Z",
      "timestamp": "2021-04-28T14:01:25.402Z"
    },
    "relationships": {
      "subj": {
        "data": {
          "id": "https://doi.org/10.17863/cam.298",
          "type": "objects"
        }
      },
      "obj": {
        "data": {
          "id": "https://doi.org/10.1162/coli_a_00263",
          "type": "objects"
        }
      }
    }
  }
}
```

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ohat)

**Comment by amgciadev** [comment]
The same issue happens with other citation relationships (cites/references) where the dataset is the target of the relationship. 

For example: all the results from this query (only showing first page of results):
 
https://api.datacite.org/events?mailto=YOUR_EMAIL_HERE&prefix=10.17863&source-id=crossref
 
should count as citations for the target objects (Cambridge DOIs) and at the moment are not showing up as citations either.

**Comment by kjgarza** [comment]
I was looking at summary stats about this today and it seems that many events still need to be processed. Here is a list that can help us to define a way to go about it 

![image](https://user-images.githubusercontent.com/1092861/129588397-f96c8be4-f30f-44dc-8933-8d222e1decb6.png)

**Comment by amgciadev** [comment]
Is there any indication of timeframes for processing these, or anything we can do to speed it up? We are exploring using DataCite badges but due to the great amount of missing links for our repository in Commons, the badges are really not useful and misleading.
