### ISSUE TITLE
Citations and References counts when using `cites` and `isCitedby` are wrongly computed.

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#752]
### Expected Behaviour

When using the relation types  `cites` and `isCitedby`  the events must be counted either in references or citations respectively. 

### Current Behaviour

Citations and References counts when using `cites` and `isCitedby` are wrongly computed.

It might affect a large number of events but not in comparison to the whole set of events

![image](https://user-images.githubusercontent.com/1092861/129571615-a3ab3202-601b-4078-b942-d3047e919ad8.png)

### Steps to Reproduce

1. step1
2. step2
3. step3
4. step4

### Hypothesis

This seems to have been caused due to a lack of regression checking in change:

https://github.com/datacite/lupo/commit/266b0465d521ab334eb33e531cc4e72793d74dac

https://github.com/datacite/lupo/issues/609

**Comment by digitaldogsbody** [comment]
The original hypothesis has been confirmed as the source of the issue and a fix has been developed. Some consideration will have to be given to what to do for historical data where it is incorrect.
