### ISSUE TITLE
REST API does not return optional affiliation properties

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/lupo#764]
[DataCite Metadata Schema 4.3](http://schema.datacite.org/meta/kernel-4.3/) introduced new optional properties for creator/contributor affiliation. These properties are settable via Fabrica and the JSON API, and are returned in the DataCite XML and JSON metadata exports from Fabrica, but do not appear in the JSON API response, where instead a list of strings is returned.

JSON API response, containing just the string "DataCite" for the affiliation of the first creator: https://api.datacite.org/dois/10.5438%2F7z70-1155
DataCite JSON export for the same DOI, containing the rich affiliation Data: https://api.datacite.org/dois/application/vnd.datacite.datacite+json/10.5438/7z70-1155

Additionally, the JSON API expects the input data of affiliation to match the format of the DataCite JSON, and will not accept data in the format it itself returns, meaning there is a discrepancy between the format required for input and output of the data.

**Comment by digitaldogsbody** [comment]
Related to: https://github.com/datacite/bracco/issues/399

**Comment by digitaldogsbody** [comment]
This data should actually be exposed correctly by adding the querystring argument `affiliation=true` to JSON API requests (e.g https://api.datacite.org/dois/10.5438%2F7z70-1155?affiliation=true).

@jonathanthiry - could you see if this meets your usecase?

**Comment by jonathanthiry** [comment]
Thanks @digitaldogsbody!

The `affiliation=true` query string works and I see that this behavior is now in [the documentation](https://support.datacite.org/docs/can-i-see-more-detailed-affiliation-information-in-the-rest-api).

It's unfortunate that the API has become inconsistent, by default:
- Getting a DOI or a list of DOIs returns affiliations as a list of strings
- Updating a DOI requires affiliations as a list of objects

It would have been nice to support updates with a list of strings if you wanted to avoid a breaking change and keep the API consistent.

**Comment by svogt0511** [comment]
@digitaldogsbody - thanks.  This allowed me to fix 2 bugs in Fabrica.
