### ISSUE TITLE
valueUri and schemeUri searches with asterisk generate error in DataCite Commons

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/lupo#847]
#### Expected Behaviour

searching valueUri and schemeUri with asterisk * retrieves results in DataCite Commons 

#### Current Behaviour

searching valueUri and schemeUri with asterisk * does not retrieve results in DataCite Commons and generates an error

#### Steps to Reproduce

1. the valueUri subproperty is indexed and can be retrieved via the api  https://api.datacite.org/dois?query=subjects.valueUri%3A*
2. but the same search in DataCite Commons generates an error: https://commons.datacite.org/doi.org?query=subjects.valueUri%3A*
3 same for schemeUri

These searches do generate results:

subjects.schemeUri:*dewey*
subjects.valueUri:*dewey*

### Context (Environment)

DataCite Commons

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2omdx)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2xydx)

**Comment by MaryHirsch** [comment]
@codycooperross should this be closed?

**Comment by codycooperross** [comment]
Yes! Resolved by datacite/datacite#969
