### ISSUE TITLE
New MDS setup does not mint DOIs

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#85]
Do the DOIs really not resolve or is it that the datbase doesnot get updated?
By a quick sample, we can see that all newly created DOIs do not resolve.

Are there Errors logs with regards to Handle?
https://app.datadoghq.com/logs?cols=%5B%22core_service%22%2C%22log_aws.awslogs.logGroup%22%2C%22log_duration%22%5D&event&from_ts=1531214317125&index=main&live=true&query=%22%5BHandle%5D+Error+updating+DOI%22&stream_sort=asc&to_ts=1531819117125

and

https://app.datadoghq.com/logs?cols=%5B%22core_service%22%2C%22log_aws.awslogs.logGroup%22%2C%22log_duration%22%5D&event&from_ts=1531733196409&index=main&live=true&query=%22Another+user+has+changed+this+record.+Please+try+again%22&stream_sort=asc&to_ts=1531819596409

When did it started?
It seems to be as early as July 16 around 10AM.

**Comment by kjgarza** [comment]
Which  services are creating DOIS with this problem?
At least Poodle and EZID API are creating DOIS with this problem.

*DOIs created by EZID*

https://doi.org/10.5061/dryad.1d9p080
Metadata:
15549248	2018-07-16 22:57:34	10.5061/DRYAD.1D9P080	1	NULL	NULL	NULL	NULL	2018-07-16 22:57:34	0	31621	NULL	http://datadryad.org/publicationBlackout	NULL	NULL	findable	NULL
Does not resolve


*DOIs created by POODLE*

https://doi.org/10.5445/IR/16090
Metadata
15551732	2018-07-17 10:55:05	10.5445/IR/16090	1	NULL	200	2018-07-17 10:55:42	NULL	2018-07-17 10:55:06	1	29856	NULL	https://publikationen.bibliothek.kit.edu/16090	NULL	text/html	findable	NULL
Does not resolve


*DOIs created by Fabrica*

**Comment by mfenner** [comment]
One big problem: `https://mds-legacy.datacite.org/doi/DOI` is not properly resolving:

```
vernon-5:~ mfenner$ curl https://mds-legacy.datacite.org/doi/10.5446/37171 -i
HTTP/2 404
date: Tue, 17 Jul 2018 11:21:12 GMT
content-type: text/html; charset=utf-8
content-length: 0
status: 404 Not Found
vary: Origin
x-request-id: 6d599277-3c3a-46a7-b867-cd82d50cee16
x-runtime: 0.002274
x-powered-by: Phusion Passenger 5.3.1
server: nginx/1.14.0 + Phusion Passenger 5.3.1
```

This call should return a 401 status. Will check Route 53 configuration.

**Comment by mfenner** [comment]
Deployed a fix via https://github.com/datacite/mastino/commit/0f5d5068746b60ec5abf86a24a7b4dc077692ff0

**Comment by mfenner** [comment]
Also need to update the nginx virtual server configuration for the mds to include `mds-legacy.datacite.org` in the list of server names.

**Comment by mfenner** [comment]
This issue has been resolved.
