### ISSUE TITLE
500 error on updating DOI

### ISSUE THREAD

**Issue by kjgarza** [datacite/lupo#91]
https://app.datadoghq.com/logs?agg_m=count&agg_q=log_aws.awslogs.logGroup&agg_t=count&cols=%5B%22core_service%22%2C%22log_aws.awslogs.logGroup%22%2C%22log_duration%22%5D&context_event=AAAAAWSw6KT2y1S-_AAAAABBV1N3NkxjRkJkZ3pyVVE4a3pSZQ&event&from_ts=1531815427813&index=main&live=false&messageDisplay=inline&panel=%7B%22timeRange%22%3A%7B%22live%22%3Atrue%2C%22from%22%3A1531815427813%2C%22to%22%3A1531988227813%7D%2C%22queryString%22%3A%22%40aws.awslogs.logGroup%3A%5C%22%2Fecs%2Fclient-api%5C%22%22%2C%22filter%22%3A%7B%22source%22%3A%22log%22%2C%22path%22%3A%22aws.awslogs.logGroup%22%2C%22value%22%3A%22%2Fecs%2Fclient-api%22%7D%7D&query=%2210.6084%2Fm9.figshare.6839096.v1%22&step=auto&stream_sort=desc&to_ts=1531976394022&viz=toplist

**Comment by mfenner** [comment]
This could be a duplicate of https://github.com/datacite/lupo/issues/84, which was just closed.

**Comment by kjgarza** [comment]
OK, I'll close it
